name: ci
on: [push, pull_request]
env:
  DOCKER_USERNAME: igagis
  # github container registry
  DOCKER_REGISTRY: ghcr.io
  IMAGE_OWNER: esp-open-sdk/esp-open-sdk
  IMAGE_NAME: esp-open-sdk
  # image version is to be updated manually when new image is to be published
  IMAGE_VERSION: 0
jobs:
  build_docker_image:
    runs-on: ubuntu-latest
    name: build docker image
    steps:
      - name: git clone
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: set environmental variables
        run: |
          echo "DOCKER_IMAGE_NAME=$DOCKER_REGISTRY/$IMAGE_OWNER/$IMAGE_NAME:$IMAGE_VERSION" >> $GITHUB_ENV
      - name: build docker image
        run: sudo docker build -t $DOCKER_IMAGE_NAME .
      - name: test
        run: |
          cd sdk/examples/blinky
          docker run -u `id -u`:`id -g` -v $(pwd):/build -w /build $DOCKER_IMAGE_NAME make
      - name: login to docker registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login $DOCKER_REGISTRY --username $DOCKER_USERNAME --password-stdin
        if: startsWith(github.ref, 'refs/heads/master')
      - name: publish image to docker hub
        run: |
          # check if the docker image already exists in the registry
          if [ "$(DOCKER_CLI_EXPERIMENTAL=enabled docker manifest inspect $DOCKER_IMAGE_NAME > /dev/null 2>&1; echo $?)" -eq 1 ]; then
            docker push $DOCKER_IMAGE_NAME
          else
            echo "docker image $DOCKER_IMAGE_NAME already exists, not pushing it"
          fi
        if: startsWith(github.ref, 'refs/heads/master')
